/**
 * POST /api/attendance/delegations/:id/proxy-mark
 *
 * Group leader marks a group member present via proxy during an active GD session.
 * Auth: Student JWT (must be the assigned leader for this delegation).
 */
import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { verifyStudentAccessToken } from '@/lib/studentAuthJwt';

export const runtime = 'nodejs';

const GD_SESSION_DURATION_MS = 600_000; // 10 minutes

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization',
};

export function OPTIONS() {
  return new NextResponse(null, { status: 204, headers: corsHeaders });
}

export async function POST(
  req: NextRequest,
  context: { params: Promise<{ id: string }> },
) {
  // ── Auth ──────────────────────────────────────────────────────────────────
  const bearerToken = req.headers.get('authorization')?.replace(/^Bearer\s+/i, '').trim() ?? '';
  if (!bearerToken) {
    return NextResponse.json({ message: 'Unauthorized' }, { status: 401, headers: corsHeaders });
  }

  let leaderId: string;
  try {
    ({ studentId: leaderId } = verifyStudentAccessToken(bearerToken));
  } catch {
    return NextResponse.json({ message: 'Invalid or expired token' }, { status: 401, headers: corsHeaders });
  }

  const { id } = await context.params;

  // ── Parse body ────────────────────────────────────────────────────────────
  let body: {
    sessionToken?: string;
    targetStudentId?: string;
    targetAdmissionNumber?: string;
    markedAt?: number;
  };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ message: 'Invalid JSON body' }, { status: 400, headers: corsHeaders });
  }

  const { sessionToken, targetStudentId, targetAdmissionNumber, markedAt } = body;

  if (!sessionToken) {
    return NextResponse.json({ message: 'sessionToken is required' }, { status: 400, headers: corsHeaders });
  }
  if (!targetStudentId) {
    return NextResponse.json({ message: 'targetStudentId is required' }, { status: 400, headers: corsHeaders });
  }
  if (!targetAdmissionNumber) {
    return NextResponse.json({ message: 'targetAdmissionNumber is required' }, { status: 400, headers: corsHeaders });
  }
  if (typeof markedAt !== 'number' || isNaN(markedAt)) {
    return NextResponse.json({ message: 'markedAt must be a Unix timestamp in milliseconds' }, { status: 400, headers: corsHeaders });
  }

  // ── Fetch delegation ──────────────────────────────────────────────────────
  const delegation = await prisma.delegation.findUnique({ where: { id } });

  if (!delegation) {
    return NextResponse.json({ message: 'Delegation not found' }, { status: 404, headers: corsHeaders });
  }

  // ── Validation 2: caller must be the assigned leader ─────────────────────
  if (delegation.leaderStudentId !== leaderId) {
    return NextResponse.json(
      { message: 'Forbidden: you are not the assigned leader for this delegation' },
      { status: 403, headers: corsHeaders },
    );
  }

  // ── Validations 3 & 4: session token + markedAt window ──────────────────
  //
  // Two accepted token formats:
  //  • Server JWT   — stored in delegation.sessionToken; session may be ended
  //                   already (offline sync). markedAt must fall within the
  //                   10-minute window from delegation.startedAt.
  //  • LOCAL token  — LOCAL-<delegationId>-<leaderStudentId>, generated by the
  //                   mobile client when /start couldn't reach the server.
  //                   markedAt must fall within delegation.validFrom–validUntil.
  //
  // The "session still active" check is intentionally removed: proxy-marks
  // recorded during the session window may be transmitted after it ends.
  const isLocalToken = sessionToken.startsWith('LOCAL-');

  if (isLocalToken) {
    // Verify format: LOCAL-<delegationId>-<leaderStudentId>
    if (sessionToken !== `LOCAL-${id}-${leaderId}`) {
      return NextResponse.json(
        { message: 'Invalid LOCAL session token' },
        { status: 400, headers: corsHeaders },
      );
    }
    // markedAt must fall within the delegation's pre-authorised validity window
    const validFromMs = Number(delegation.validFrom);
    const validUntilMs = Number(delegation.validUntil);
    if (markedAt < validFromMs || markedAt > validUntilMs) {
      return NextResponse.json(
        { message: 'markedAt is outside the delegation validity window' },
        { status: 400, headers: corsHeaders },
      );
    }
    // If /start was never called online, record the LOCAL token for audit and
    // set an approximate startedAt so downstream queries have a reference time.
    if (!delegation.sessionToken) {
      await prisma.delegation.update({
        where: { id },
        data: {
          sessionToken,                                         // store LOCAL token for audit
          startedAt: new Date(Number(delegation.validFrom)),   // use window open as proxy start
        },
      });
    }
  } else {
    // Server JWT path — string equality against DB value is sufficient.
    // JWT expiry is intentionally NOT re-verified: offline sessions may be
    // synced after the 10-min JWT window; the leader's auth JWT is the
    // authoritative identity proof.
    if (!delegation.sessionToken) {
      return NextResponse.json(
        { message: 'Session has not been started yet — call /start first' },
        { status: 400, headers: corsHeaders },
      );
    }
    if (delegation.sessionToken !== sessionToken) {
      return NextResponse.json({ message: 'Invalid session token' }, { status: 400, headers: corsHeaders });
    }
    // Validate markedAt against the actual session start (client-reported time
    // must correspond to the live session window).
    if (!delegation.startedAt) {
      return NextResponse.json(
        { message: 'Session start time not recorded' },
        { status: 400, headers: corsHeaders },
      );
    }
    const sessionStartMs = delegation.startedAt.getTime();
    if (markedAt < sessionStartMs || markedAt > sessionStartMs + GD_SESSION_DURATION_MS) {
      return NextResponse.json(
        { message: 'markedAt is outside the active session window (10 minutes from session start)' },
        { status: 400, headers: corsHeaders },
      );
    }
  }

  // ── Validation 5: targetStudent must be an active group member ───────────
  const membership = await prisma.groupMember.findFirst({
    where: { groupId: delegation.groupId, studentId: targetStudentId, leftAt: null },
  });
  if (!membership) {
    return NextResponse.json(
      { message: 'targetStudentId is not an active member of this group' },
      { status: 400, headers: corsHeaders },
    );
  }

  // ── Validation 6: cannot proxy-mark the leader themselves ────────────────
  if (targetStudentId === leaderId) {
    return NextResponse.json(
      { message: 'Leader is automatically marked on session start — do not re-record' },
      { status: 400, headers: corsHeaders },
    );
  }

  // ── Duplicate check (unique: studentId, unitCode, lectureRoom, sessionStart) ─
  // For LOCAL tokens where /start was never called online, use validFrom as a
  // stable sessionStart so the unique constraint is consistent across all
  // proxy-mark calls for the same delegation.
  const sessionStartDate =
    delegation.startedAt ?? new Date(Number(delegation.validFrom));
  const existing = await prisma.offlineAttendanceRecord.findUnique({
    where: {
      studentId_unitCode_lectureRoom_sessionStart: {
        studentId: targetStudentId,
        unitCode: delegation.unitCode,
        lectureRoom: delegation.roomCode,
        sessionStart: sessionStartDate,
      },
    },
  });
  if (existing) {
    return NextResponse.json(
      { message: 'Student already marked present for this session' },
      { status: 409, headers: corsHeaders },
    );
  }

  // ── Write attendance record ───────────────────────────────────────────────
  await prisma.offlineAttendanceRecord.create({
    data: {
      studentId: targetStudentId,
      admissionNumber: targetAdmissionNumber,
      unitCode: delegation.unitCode,
      lectureRoom: delegation.roomCode,
      lessonType: 'GD',
      sessionStart: sessionStartDate,
      scannedAt: new Date(markedAt),
      method: 'proxy_leader',
      delegationId: id,
      markedByLecturerId: null,
      institutionId: delegation.institutionId ?? null,
    },
  });

  return NextResponse.json(
    {
      message: 'Attendance recorded',
      studentId: targetStudentId,
      admissionNumber: targetAdmissionNumber,
      attendanceMethod: 'proxy_leader',
      delegationId: id,
      markedAt,
    },
    { status: 201, headers: corsHeaders },
  );
}
