/**
 * lib/timetableBookingSync.ts
 *
 * Keeps Booking records in sync with Timetable entries so that the Room
 * Manager pages reflect timetable-driven room reservations.
 *
 * Strategy
 * ─────────
 *  • On CREATE  → generate one Booking per weekly occurrence for the next
 *                 WEEKS_AHEAD weeks (idempotent via idempotencyKey).
 *  • On CANCEL  → mark all future Bookings for this entry as "cancelled".
 *  • On RESCHEDULE (permanent) → cancel old bookings + create new ones with
 *                 the updated day / times.
 *  • On DELETE  → same as cancel.
 *
 * idempotencyKey format:  timetable:{entryId}:{YYYY-MM-DD}
 */

import { prisma } from "@/lib/prisma";
import { BookingStatus } from "@prisma/client";
import { recomputeRoomStatus } from "@/lib/roomBookingService";

/** How many weeks ahead to pre-generate bookings (≈ one semester). */
const WEEKS_AHEAD = 16;

const DAY_TO_DOW: Record<string, number> = {
  Sunday: 0,
  Monday: 1,
  Tuesday: 2,
  Wednesday: 3,
  Thursday: 4,
  Friday: 5,
  Saturday: 6,
};

/** Clone a date and set UTC hours/minutes from an "HH:MM" string.
 * Times in timetable entries are treated as UTC so they match what the
 * department admin set and display correctly on the facilities-manager pages. */
function applyTime(base: Date, hhmm: string): Date {
  const [h, m] = hhmm.split(":").map(Number);
  const d = new Date(base);
  d.setUTCHours(h, m, 0, 0);
  return d;
}

/** Returns the next WEEKS_AHEAD occurrences of `day` starting from today. */
function getOccurrences(
  day: string,
  startTime: string,
  endTime: string,
): { startAt: Date; endAt: Date; dateKey: string }[] {
  const dow = DAY_TO_DOW[day];
  if (dow === undefined) return [];

  const today = new Date();
  today.setUTCHours(0, 0, 0, 0);

  const daysUntil = (dow - today.getUTCDay() + 7) % 7;
  const first = new Date(today);
  first.setUTCDate(today.getUTCDate() + daysUntil);

  const results: { startAt: Date; endAt: Date; dateKey: string }[] = [];
  for (let w = 0; w < WEEKS_AHEAD; w++) {
    const base = new Date(first);
    base.setUTCDate(first.getUTCDate() + w * 7);
    results.push({
      startAt: applyTime(base, startTime),
      endAt: applyTime(base, endTime),
      dateKey: base.toISOString().slice(0, 10),
    });
  }
  return results;
}

export interface TimetableEntryData {
  id: string;
  roomId: string;
  lecturerId: string;
  unitId: string;
  unitCode?: string | null;
  day: string;
  startTime: string;
  endTime: string;
}

/**
 * Creates recurring Booking records for the next WEEKS_AHEAD weeks.
 * Uses `skipDuplicates: true` so re-running is safe.
 * Returns the number of bookings actually inserted.
 */
export async function createTimetableBookings(
  entry: TimetableEntryData,
): Promise<number> {
  const occurrences = getOccurrences(entry.day, entry.startTime, entry.endTime);
  if (!occurrences.length) return 0;

  const result = await prisma.booking.createMany({
    data: occurrences.map(({ startAt, endAt, dateKey }) => ({
      roomId: entry.roomId,
      lecturerId: entry.lecturerId,
      unitId: entry.unitId,
      unitCode: entry.unitCode ?? null,
      startAt,
      endAt,
      status: BookingStatus.reserved,
      idempotencyKey: `timetable:${entry.id}:${dateKey}`,
    })),
    skipDuplicates: true,
  });

  // Recompute room status so it reflects the new reservations immediately
  if (result.count > 0) {
    await prisma.$transaction(async (tx) => {
      await recomputeRoomStatus(tx, entry.roomId, "timetable_booking_created", null);
    });
  }

  return result.count;
}

/**
 * Creates a booking for just the single next occurrence of the given day/time.
 * Used for temporary reschedules where only one slot needs to be reserved.
 */
export async function createNextOccurrenceBooking(
  entry: TimetableEntryData,
): Promise<number> {
  const occurrences = getOccurrences(entry.day, entry.startTime, entry.endTime);
  if (!occurrences.length) return 0;

  const { startAt, endAt, dateKey } = occurrences[0];

  const result = await prisma.booking.createMany({
    data: [{
      roomId: entry.roomId,
      lecturerId: entry.lecturerId,
      unitId: entry.unitId,
      unitCode: entry.unitCode ?? null,
      startAt,
      endAt,
      status: BookingStatus.reserved,
      idempotencyKey: `timetable:${entry.id}:${dateKey}`,
    }],
    skipDuplicates: true,
  });

  if (result.count > 0) {
    await prisma.$transaction(async (tx) => {
      await recomputeRoomStatus(tx, entry.roomId, "timetable_booking_created", null);
    });
  }

  return result.count;
}

/**
 * Marks all FUTURE bookings generated by this timetable entry as cancelled.
 * Past bookings are left untouched so historical data is preserved.
 */
export async function cancelTimetableBookings(entryId: string): Promise<void> {
  // Find affected rooms before cancelling
  const affectedBookings = await prisma.booking.findMany({
    where: {
      idempotencyKey: { startsWith: `timetable:${entryId}:` },
      startAt: { gte: new Date() },
      status: BookingStatus.reserved,
    },
    select: { roomId: true },
    distinct: ["roomId"],
  });

  await prisma.booking.updateMany({
    where: {
      idempotencyKey: { startsWith: `timetable:${entryId}:` },
      startAt: { gte: new Date() },
      status: BookingStatus.reserved,
    },
    data: { status: BookingStatus.cancelled },
  });

  // Recompute status for each affected room
  for (const { roomId } of affectedBookings) {
    await prisma.$transaction(async (tx) => {
      await recomputeRoomStatus(tx, roomId, "timetable_booking_cancelled", null);
    });
  }
}

/**
 * Permanently reschedules: cancels old bookings and generates new ones.
 * The `entry` object should already have the updated day/startTime/endTime.
 */
export async function rescheduleTimetableBookings(
  entry: TimetableEntryData,
): Promise<void> {
  await cancelTimetableBookings(entry.id);
  await createTimetableBookings(entry);
}
